CPPC    = g++
FLAGS   = -W -Wall -ansi
LFLAGS  =


EXE = life32_v01.exe
OBJ = life32_v01.o
SRC = life32_v01.cpp



all: compile


compile:
	$(CPPC) $(SRC) -o $(EXE) $(FLAGS) $(LFLAGS)


clean:
	@rm -rf *.o


run:
	$(EXE)


